name: VerifyListener
version: 1.0
main: com.example.VerifyListener
api-version: '26.2'

commands:
  home:
    description: 傳送回家
    usage: /home
    permission: verifylistener.home
    permission-message: "§c你沒有使用 /home 的權限"

  set_place:
    description: 設定自己的暫時傳送點
    usage: /set_place
    permission: verifylistener.set_place
    permission-message: "§c你沒有設定暫時傳送點的權限"

  back:
    description: 傳送到自己的暫時傳送點
    usage: /back
    permission: verifylistener.back
    permission-message: "§c你沒有使用暫時傳送點的權限"

permissions:
  verifylistener.home:
    description: 允許使用 /home
    default: false

  verifylistener.set_place:
    description: 允許設定自己的暫時傳送點
    default: false

  verifylistener.back:
    description: 允許傳送到自己的暫時傳送點
    default: false